version: '3.7'

services:

  minesweeper:
    container_name: minesweeper
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - './:/home/node/app'
      - '/home/node/app/node_modules'
    ports:
      - 7777:7777
    environment:
      CHOKIDAR_USEPOLLING: 'true'
    stdin_open: true
    tty: true
